.Dd July 24, 2015
.Dt XOREOS 6
.Os
.Sh NAME
.Nm xoreos
.Nd reimplementation of BioWare's Aurora engine
.Sh SYNOPSIS
xoreos
.Op Ar options
.Op Ar target
.Sh DESCRIPTION
.Nm xoreos
is an open source implementation of BioWare's Aurora engine and its
derivatives, licensed under the terms of the GNU General Public
License version 3 (or later).
The goal is to have all games using this engine working in a portable manner.
.Pp
.Sy The following games are valid targets for xoreos:
.Bl -bullet -compact
.It
Neverwinter Nights
.It
Neverwinter Nights 2
.It
Knights of the Old Republic
.It
Knights of the Old Republic II: The Sith Lords
.It
Jade Empire
.It
Sonic Chronicles: The Dark Brotherhood
.It
The Witcher
.It
Dragon Age: Origins
.It
Dragon Age II
.El
.Ss Running xoreos
First, you need to fully install and/or copy the game you want to play
with
.Nm
onto your hard disk.
How you do this depends on the game,
your operating system and where/how you have bought the game.
.Pp
.Nm
does not yet have a launcher GUI or anything like this.
You need to start it from the command line.
Run xoreos with the command line option
.Fl Fl help
to get a help text about further command line options.
.Pp
The quickest way to start a game in path
.Pa /path/to/game/
would be to call:
.Pp
.Dl $ xoreos -p/path/to/game/
.Pp
If you're on Windows and the path is, say,
.Pa D:\ePath\eTo\eGame\e , call :
.Pp
.Dl $ xoreos -pD:\ePath\eTo\eGame\e
.Ss Config file
In general,
.Nm
can read the configuration which game to run from either the command
line, a config file or both.
Additionally, when you first specify a new game on the command line,
.Nm
will add a related entry in the config file (creating it first, if
necessary).
.Pp
To accurately identify a specific instance of an installed game,
.Nm
uses the concept of a
.Dq target .
Each target has a separate section in the config file,
and each of their options apply only to that target.
The special target
.Dq xoreos
is a global section applying to all games,
although the same option in a game target overrides the global option.
.Pp
.Sy For example:
.Bd -literal -offset Ds
[xoreos]
width=1024
height=768
fullscreen=false

[nwn]
path=/home/drmccoy/games/nwn/
fullscreen=true
volume_music=0.500000
volume_sfx=0.850000
volume_voice=0.850000
.Ed
.Pp
You can then start the game with the target
.Dq nwn
with
.Pp
.Dl $ xoreos nwn
.Pp
and
.Nm
will do the rest.
This will start the game in the path
.Pa /home/drmccoy/games/nwn/ ,
running it in fullscreen at 1024\(mu768.
.Pp
As you can see with the volume options,
.Nm
also saves settings you made in the game' actual GUI into the
target's section of the config file.
.Pp
The place where
.Nm
expects the config file depends on your operating system:
.Bl -bullet -compact
.It
On GNU/Linux, the place is
.Pa $XDG_CONFIG_HOME/xoreos/xoreos.conf .
.Ev XDG_CONFIG_HOME
defaults to
.Pa $HOME/.config/ .
.It
On Mac OS X, the place is
.Pa $HOME/Library/Preferences/xoreos/xoreos.conf .
.It
On Windows,
.Pa xoreos.conf
is in the subdirectory
.Pa xoreos
in either
.Ev $APPDATA
or
.Ev $USERPROFILE ,
depending on your Windows version.
.El
.Sh OPTIONS
.Bl -tag -width Ds -compact
.It Fl Fl help
Show a help text and exit.
.It Fl Fl version
Show version information and exit.
.It Fl c Ar file
.It Fl Fl config= Ns Ar file
Load the config from file
.Ar file .
.It Fl p Ar dir
.It Fl Fl path= Ns Ar dir
Override the game path with
.Ar dir .
.It Fl w Ar size
.It Fl Fl width= Ns Ar size
Set the window's width to
.Ar size .
.It Fl h Ar size
.It Fl Fl height= Ns Ar size
Set the window's height to
.Ar size .
.It Fl f Ar bool
.It Fl Fl fullscreen= Ns Ar bool
Switch fullscreen on/off.
.It Fl k Ar bool
.It Fl Fl skipvideos= Ns Ar bool
Disable videos on/off.
.It Fl v Ar vol
.It Fl Fl volume= Ns Ar vol
Set global volume to
.Ar vol .
.It Fl m Ar vol
.It Fl Fl volume_music= Ns Ar vol
Set music volume to
.Ar vol .
.It Fl s Ar vol
.It Fl Fl volume_sfx= Ns Ar vol
Set SFX volume to
.Ar vol .
.It Fl o Ar vol
.It Fl Fl volume_voice= Ns Ar vol
Set voice volume to
.Ar vol .
.It Fl i Ar vol
.It Fl Fl volume_video= Ns Ar vol
Set video volume to
.Ar vol .
.It Fl q Ar lang
.It Fl Fl lang= Ns Ar lang
Set the game's language.
.It Fl Fl langtext= Ns Ar lang
Set the game's text language.
.It Fl Fl langvoice= Ns Ar lang
Set the game's voice language.
.It Fl d Ar dlvl
.It Fl Fl debug= Ns Ar dlvl
Set the debug channel verbosities to
.Ar dlvl .
.It Fl Fl debuggl= Ns Ar bool
Create OpenGL debug context.
.It Fl Fl listdebug
List all available debug channels.
.It Fl Fl listlangs
List all available languages for this target.
.It Fl Fl logfile= Ns Ar file
Write all debug output into this file too.
.It Fl Fl nologfile= Ns Ar bool
Don't write a log file.
.It Fl Fl consolelog= Ns Ar file
Write all debug console output into this file too.
.It Fl Fl noconsolelog= Ns Ar bool
Don't write a debug console log file.
.El
.Bl -tag -width Ds
.It Ar file
Absolute or relative path to a file.
.It Ar dir
Absolute or relative path to a directory.
.It Ar size
A positive integer.
.It Ar bool
.Dq true ,
.Dq yes ,
.Dq y ,
.Dq on ,
and
.Dq 1
are true, everything else is false.
.It Ar vol
A double ranging from 0.0 (min) \(en 1.0 (max).
.It Ar lang
A language identifier.
Full name, ISO 639-1 or ISO 639-2 language code;
or IETF language tag with ISO 639-1 and ISO 3166-1 country code.
Examples: en, de_de, hun, Czech, zh-tw, zh_cn, zh-cht, zh-chs.
.It Ar dlvl
A comma-separated list of a debug channel name, a colon and the desired
verbosity level. For example: GGraphics:4,GVideo:1,EEvents:9.
Use
.Dq All
to refer to all debug channels.
OpenGL debug channels need the debuggl option to be enabled and require
OpenGL driver support of the GL_ARB_debug_output extension.
.El
.Pp
Long-form command line option, like
.Fl Fl skipvideos ,
map directly to config options.
Options given on the command line will override any
options found in the config file for this session,
but will not save back to that config file.
.Sh EXAMPLES
.Dl $ xoreos -p/path/to/nwn/
.Pp
.Nm
will start the game in
.Pa /path/to/nwn/ .
Should a target with this path not yet exist in the config file,
.Nm
will create one named
.Dq nwn .
.Pp
.Dl $ xoreos -p/path/to/nwn/ foobar
.Pp
.Nm
will start the game in
.Pa /path/to/nwn/ .
If a target
.Dq foobar
does not yet exist in the config file,
.Nm
will create it.
.Pp
.Dl $ xoreos nwn
.Pp
.Nm
will start the game specified by target
.Dq nwn ,
which must exist in the config file already.
.Sh SEE ALSO
More information about the xoreos project can be found on
.Lk https://xoreos.org/ "its website"
and
.Lk https://wiki.xoreos.org/ "its wiki" .
.Sh AUTHORS
This program is part of the xoreos projects, and was written by
the xoreos team.
Please see the
.Pa AUTHORS
file for details.
